### ISSUE TITLE
Hammer Search Paths add a slash at the end of it, causing VPK's not to load.

### ISSUE THREAD

**Issue by Demez** [Demez/Quiver#21]
![2019-05-10_16-17-47_hammer_Hammer](https://user-images.githubusercontent.com/30940677/57554388-50f6db80-733f-11e9-992c-aa7a17c42555.png)

**Comment by kaskadas** [comment]
VPKs are actually loaded, the issue here is the filesystem not scanning vpks in the function FindFirst(), which is essentiall for the material/model browser

**Comment by Demez** [comment]
Hammer itself isn't actually loading any files from it seemingly, since it just says it can't find `editor/wireframe` and then crashes.

**Comment by JJL772** [comment]
Is this fixed in the latest update to dev or is it still an issue?

**Comment by Demez** [comment]
This is still an issue currently

**Comment by Demez** [comment]
Fixed by @Spirrwell
